version: '3.8'

services:
  app:
    image: ghcr.io/orakysec/ferreira3dstudio:latest
    networks:
      - YkaroNET
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=YkaroNET"
        # Redirecionamento HTTP -> HTTPS
        - "traefik.http.routers.f3d-http.rule=Host(`ferreira3d.com`, `www.ferreira3d.com`)"
        - "traefik.http.routers.f3d-http.entrypoints=web"
        - "traefik.http.routers.f3d-http.middlewares=f3d-https"
        - "traefik.http.middlewares.f3d-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.f3d-https.redirectscheme.permanent=true"
        # Rota HTTPS segura
        - "traefik.http.routers.f3d-https.rule=Host(`ferreira3d.com`, `www.ferreira3d.com`)"
        - "traefik.http.routers.f3d-https.entrypoints=websecure"
        - "traefik.http.routers.f3d-https.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.f3d-https.loadbalancer.server.port=80"

networks:
  YkaroNET:
    external: true
